---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:22.04
provisioner:
  name: ansible
  log: true
  inventory:
    links:
       group_vars: inventory/
verifier:
  name: ansible
  options:
    v: 2
